### PR TITLE
Update locality and neighbourhood records

### LINKED ISSUE #1903: QA localities and neighbourhoods in Indonesia
https://spelunker.whosonfirst.org/id/85632203/descendants/?exclude=nullisland&placetype=locality
https://spelunker.whosonfirst.org/id/85632203/descendants/?exclude=nullisland&placetype=neighbourhood

Let's QA and update the neighbourhood and locality placetypes in Indonesia, as needed.

### PR DESCRIPTION
**Pull request by stepps00**
Replaces #10.

Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/1903.

- [x] Update existing multi-part locality geometries to single-part geometries
- [x] Update geometries for top-tier (~40ish) localities
- [x] Add/update neighbourhood records in Surabaya
- [x] Add/update neighbourhood records in Jakarta
- [x] Add Indonesian names to all new neighbourhood records
- [x] Update `wof:lang_x_*` properties
- [x] QA superseding/coterminous properties of Jakarta region/locality records
- [x] PIP
- [x] Validate

### CODE REVIEW

**Comment by stepps00** [comment]
2b3cafd: Converts multi-part locality polygons to single-part, preferring the largest part of the geometry.
6b3e61e: Updates largest localities with hand-curated polygons, drawn in QGIS
7cc5651: Clips any overlapping Quattroshapes geometries to the new hand-curated locality polygons.
05fa4fe: Deprecate and flag `"mz:is_current":0` properties on any leftover, overlapping Quattroshapes geometries that fall inside/overlap new WOF geometries. After this commit, no "current" locality geometries will overlap.
5058295: Adds new neighbourhoods in Surabaya
8562ded: Deprecates non-matching neighbourhood points in Surabaya
8b3e2d6: Deprecates non-matching neighbourhood points in Jakarta
2071f05: Deprecates non-matching neighbourhood polygons in Jakarta
4d2bcf7: Updates and adds new neighbourhoods in Jakarta. Includes superseding, storing existing geometries as alt geometries, and tries to retain existing centroids whenever possible.
3076410 and 5232cd9: Adds Indonesian (`name:ind_x_preferred`) name properties to neighbourhood and locality records updated in previous commits
c6108c6: Adds / corrects `wof:lang_x_*` properties for all current admin records in this repo.
c1e16b9 and 65a755a: Updates `mz:min_zoom` values for leftover locality records.
6598587: Deprecates leftover, non-matching locality points under hand-curated localities.
9e462fc: Includes all PIP work for this branch.

**Comment by stepps00** [comment]
This PR is ready for review. I've exported all current admin records in this repo and the changes generally look good - with some work potentially needed to:

- locality points
- Superseding around Jakarta (locality v neighbourhood)

Some screenshots of new neighbourhood polygon coverage, visualized in QGIS:

Surabaya Neighbourhoods:
Screen Shot 2021-02-18 at 3 00 54 PM

Jakarta Neighbourhoods:
Screen Shot 2021-02-18 at 3 00 46 PM

**Comment by nvkelso** [comment]
Let's review this one in screen sharing later this week, please. I'd like to take time to discuss the locality work: new shapes look good but I'm unclear how the mix of new locality polygon and point records interact and the diff is too big to pinhole thru. 

Maybe part of this is resolved in https://github.com/whosonfirst-data/whosonfirst-data-admin-id/pull/11/commits/05fa4fef44d1ce08ab1e2ce65d62b281b487acff? 

Are the original popcorn locality shapes being preserved as alt geoms – I only see the clean new geoms stored as default in https://github.com/whosonfirst-data/whosonfirst-data-admin-id/commit/6b3e61e6ba7f563b8b4118d71c5d19c51ac8e584.

**Comment by stepps00** [comment]
> Let's review this one in screen sharing later this week, please. I'd like to take time to discuss the locality work: new shapes look good but I'm unclear how the mix of new locality polygon and point records interact and the diff is too big to pinhole thru.

Sure, I will collect all current records and place them into a document to review.

> Are the original popcorn locality shapes being preserved as alt geoms – I only see the clean new geoms stored as default in 6b3e61e.

Yes, the original popcorn-shaped QS geometries are stored as alt-geometries. This work was done on any current, multi-part geometry - they were converted to single-part geometries, storing the existing geometry as an alt file. Example:

- ["Kediri" record on main branch](https://github.com/whosonfirst-data/whosonfirst-data-admin-id/blob/master/data/102/020/231/102020231.geojson)

- ["Kediri" record on this branch](https://github.com/whosonfirst-data/whosonfirst-data-admin-id/blob/stepps00/updates/data/102/020/231/102020231.geojson) (updated to be single part)
- ["Kediri" alt file on this branch](https://github.com/whosonfirst-data/whosonfirst-data-admin-id/blob/stepps00/updates/data/102/020/231/102020231-alt-quattroshapes.geojson) (existing geom now stored as alt)

**Comment by nvkelso** [comment]
I see the alt geoms now, thanks!

**Comment by nvkelso** [comment]
Noting that other countries suffer from popcorn localities can be determined looking upstream at Quattroshapes [makefile](https://github.com/foursquare/quattroshapes/blob/master/open_administrative_data/Makefile) for countries that were made using `quattroshapes_localities_priority_and_extras_master_post_diss_attr2.shp` file.

These are the original 16 countries with popcorn shapes locality from quattroshapes

- bra_localities_qs.shp:
- idn_localities_qs.shp:
- mys_localities_qs.shp:
- tha_localities_qs.shp:
- kor_localities_qs.shp:
- twn_localities_qs.shp:
- chn_localities_qs.shp:
- ind_localities_qs.shp:
- aus_localities_qs.shp:
- jpn_localities_qs.shp:
- sgp_localities_qs.shp:
- gbr_localities_qs.shp:
- tur_localities_qs.shp:
- chl_localities_qs.shp:
- rus_localities_qs.shp:
- mex_localities_qs.shp:

**Comment by nvkelso** [comment]
Please add some screenshots showing the changes to the popcorn – which pieces burned and were picked out, which were caramelized; and the salt and pepper of locality points inside/outisde of those feature. 

Likely the mz:min_zoom should be set on locality points outside of popcorn to 12, and inside curated (freshly digitized) locality polygons to zoom 13. If we have new neighbourhoods there those locality points should likely be deprecated (with quick pass to see if easy superseding).

**Comment by stepps00** [comment]
Screen Shot 2021-02-26 at 4 05 13 PM

This is the area around Jakarta. Purple shapes are existing geometries of WOF localities, orange shapes are the updated geometries. In this area, many of the multi-part "island" features have been converted to single-part/non-overlapping geometries.

Screen Shot 2021-02-26 at 4 10 23 PM
Similar to the above image, in this area, we're preferring single part geometries. The hand-curated geometry of the main city is smaller in this case.

Screen Shot 2021-02-26 at 4 11 03 PM

A single multi-part geometry is highlighted (above), which has been converted into a single-part geometry (below).

Screen Shot 2021-02-26 at 4 11 27 PM

As the last to images show, each of the multi-part locality geometries have been converted to single-part geometries. The multi-part features were exploded into single-parts, and the part with the largest area was promoted to the "default" geometry, existing geometries were stored as alt geometries.

This work doesn't fix all of the issues at the locality placetype in Indonesia, but it puts the records and geometries in a much better position for future updates.

**Comment by stepps00** [comment]
A few more images.. purple shapes are the existing locality geometries, orange shapes are the new, updated locality geometries:

Screen Shot 2021-02-26 at 4 27 13 PM
Screen Shot 2021-02-26 at 4 26 54 PM
Screen Shot 2021-02-26 at 4 26 33 PM

**Comment by nvkelso** [comment]
Love to see the images. Can you add some for the remaining locality points, too?

**Comment by stepps00** [comment]
Here are some images showing the coverage of locaity points (mostly GeoNames-sourced). Each red dot represents one locality record and orange is new locality polygons (min_zoom will change for red dots inside and outside of the orange polygons):

Screen Shot 2021-03-01 at 12 10 02 PM
_Around Jakarta_

Screen Shot 2021-03-01 at 12 09 48 PM
_Around Waingapu_

Screen Shot 2021-03-01 at 12 09 29 PM
_Around Palopo_

**Comment by stepps00** [comment]
@nvkelso - the three most recent commits take care of issues raised [in this comment](https://github.com/whosonfirst-data/whosonfirst-data-admin-id/pull/11#issuecomment-786237185). This PR should be ready to PIP, so I've kicked that off and will add a new commit with updated hierarchies/parent_ids when complete.

**Comment by stepps00** [comment]
Probably best to QA changes here: https://github.com/whosonfirst-data/whosonfirst-data-admin-id/tree/stepps00/updates/data

**Comment by nvkelso** [comment]
Looking good!

**Comment by stepps00** [comment]
The most recent commit in this PR includes PIP work. I'm going to do a round of QA and validate all changes, then likely merge if all looks good.

**Comment by stepps00** [comment]
I've PIPd and validated the changes in this branch. Flagging @nvkelso for review.. once approved, I'll merge these changes.

**Review by nvkelso — APPROVED** [review]
LGTM

**Pull request merged**
